name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run flake8 lint
        run: flake8 app --max-line-length=120

      - name: Run tests
        run: pytest tests

      - name: Build Docker image
        run: docker build -t fastapi-homepage:latest .

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@0.28.0

      - name: Run Trivy scan on image
        run: trivy image --severity HIGH,CRITICAL --exit-code 1 fastapi-homepage:latest

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
