name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Run flake8 lint
        run: flake8 app --max-line-length=120 --ignore=E302,F401

      - name: Run tests
        run: pytest tests

      - name: Build Docker image
        run: docker build -t fastapi-homepage:latest .

      - name: List local docker images
        run: docker images

      - name: Set up Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: fastapi-homepage:latest
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-files: .trivyignore
